import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const materiasPrimas = [
  // ─── SOLVENTES ───────────────────────────────────────────────────────────
  {
    nome_comercial: 'Álcool Etílico 96%',
    nome_quimico: 'Etanol',
    numero_cas: '64-17-5',
    categoria: 'Solventes',
    subcategoria: 'Solventes polares próticos',
    aparencia: 'Líquido incolor, odor característico',
    ph_solucao: '7.0',
    densidade: '0.806 g/mL',
    solubilidade_agua: 'Miscível',
    faixa_uso_tipica: '10% - 80%',
    funcao_principal: 'Solvente, agente de limpeza, veículo',
    sinergias: JSON.stringify(['Isopropanol', 'Água']),
    incompatibilidades: JSON.stringify(['Oxidantes fortes', 'Ácido perclórico']),
    ph_estabilidade: '1-14',
    restricoes_anvisa: 'Resolução RDC 26/2015 para saneantes',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Alta (>90% em 5 dias, OCDE 301)',
    origem: 'vegetal',
    certificacoes: JSON.stringify(['Biodegradável', 'Bio-based']),
    fornecedores: JSON.stringify(['Copersucar', 'Raízen', 'São Martinho']),
    custo_min: 3.5,
    custo_max: 5.0,
    disponibilidade: 'alta',
    aplicacoes_tipicas: JSON.stringify(['Limpeza Industrial', 'Saneantes', 'Automotivo']),
    notas_tecnicas: 'Preferir origem vegetal (cana) para claims sustentáveis. Atenção ao ponto de fulgor (13°C).',
  },
  {
    nome_comercial: 'Isopropanol (IPA)',
    nome_quimico: 'Propan-2-ol',
    numero_cas: '67-63-0',
    categoria: 'Solventes',
    subcategoria: 'Solventes polares próticos',
    aparencia: 'Líquido incolor, odor característico',
    ph_solucao: '7.0',
    densidade: '0.786 g/mL',
    solubilidade_agua: 'Miscível',
    faixa_uso_tipica: '10% - 70%',
    funcao_principal: 'Solvente, desengraxante, secante rápido',
    sinergias: JSON.stringify(['Álcool Etílico', 'Água']),
    incompatibilidades: JSON.stringify(['Oxidantes fortes', 'Cloroformo']),
    ph_estabilidade: '1-14',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Alta',
    origem: 'petroleo',
    fornecedores: JSON.stringify(['Braskem', 'Elekeiroz']),
    custo_min: 5.0,
    custo_max: 8.0,
    disponibilidade: 'alta',
    aplicacoes_tipicas: JSON.stringify(['Limpeza Industrial', 'Automotivo', 'Eletrônica']),
    notas_tecnicas: 'Excelente para remoção de óleos leves e gorduras. Evapora completamente sem resíduo.',
  },
  {
    nome_comercial: 'Acetona',
    nome_quimico: 'Propan-2-ona',
    numero_cas: '67-64-1',
    categoria: 'Solventes',
    subcategoria: 'Solventes polares apróticos',
    aparencia: 'Líquido incolor, odor frutal característico',
    ph_solucao: '7.0',
    densidade: '0.791 g/mL',
    solubilidade_agua: 'Miscível',
    faixa_uso_tipica: '5% - 50%',
    funcao_principal: 'Solvente forte para resinas e polímeros',
    sinergias: JSON.stringify(['Tolueno', 'Xileno']),
    incompatibilidades: JSON.stringify(['Oxidantes', 'Bases fortes', 'Clorofórmio']),
    ph_estabilidade: '5-9',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Alta',
    origem: 'petroleo',
    fornecedores: JSON.stringify(['Elekeiroz', 'Iquine']),
    custo_min: 4.5,
    custo_max: 7.0,
    disponibilidade: 'alta',
    aplicacoes_tipicas: JSON.stringify(['Tintas e Vernizes', 'Limpeza Industrial', 'Automotivo']),
    notas_tecnicas: 'Alto VOC. Ponto de fulgor -18°C — produto inflamável. Não usar em formulações com claims "Zero VOC".',
  },
  {
    nome_comercial: 'D-Limoneno',
    nome_quimico: '(R)-(+)-Limoneno',
    numero_cas: '5989-27-5',
    categoria: 'Solventes',
    subcategoria: 'Biossolventes',
    aparencia: 'Líquido incolor a amarelo pálido, odor cítrico',
    ph_solucao: '7.0',
    densidade: '0.841 g/mL',
    solubilidade_agua: 'Praticamente insolúvel (0.013 g/L)',
    faixa_uso_tipica: '1% - 15%',
    funcao_principal: 'Biossolvente, agente de limpeza, odorizante',
    sinergias: JSON.stringify(['Tensoativos não-iônicos', 'Álcool etílico']),
    incompatibilidades: JSON.stringify(['Oxidantes', 'Borrachas naturais']),
    ph_estabilidade: '5-9',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Alta (>90%)',
    origem: 'vegetal',
    certificacoes: JSON.stringify(['Bio-based', 'Biodegradável']),
    fornecedores: JSON.stringify(['Citroleo', 'Citrus Brasil']),
    custo_min: 8.0,
    custo_max: 18.0,
    disponibilidade: 'media',
    aplicacoes_tipicas: JSON.stringify(['Limpeza Industrial', 'Automotivo', 'Saneantes']),
    notas_tecnicas: 'Alergênico em fragrâncias (IFRA/REACH) acima de 0.01% em leave-on. Ótimo para claims bio/verde.',
  },
  {
    nome_comercial: 'DGBE (Dipropilenoglicol Butil Éter)',
    nome_quimico: 'Dipropilenoglicol monobutil éter',
    numero_cas: '29911-28-2',
    categoria: 'Solventes',
    subcategoria: 'Solventes polares apróticos',
    aparencia: 'Líquido incolor, odor suave',
    ph_solucao: '7.0',
    densidade: '0.906 g/mL',
    solubilidade_agua: 'Miscível',
    faixa_uso_tipica: '2% - 10%',
    funcao_principal: 'Co-solvente, coalescente, agente de acoplamento',
    sinergias: JSON.stringify(['LAS', 'Álcool etoxilado']),
    incompatibilidades: JSON.stringify(['Oxidantes fortes']),
    ph_estabilidade: '1-14',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Boa',
    origem: 'petroleo',
    fornecedores: JSON.stringify(['Dow Chemical', 'Eastman']),
    custo_min: 12.0,
    custo_max: 20.0,
    disponibilidade: 'media',
    aplicacoes_tipicas: JSON.stringify(['Limpeza Industrial', 'Tintas e Vernizes']),
    notas_tecnicas: 'Excelente coalescente para tintas aquosas. Baixo VOC comparado a solventes aromáticos.',
  },
  // ─── TENSOATIVOS ANIÔNICOS ────────────────────────────────────────────────
  {
    nome_comercial: 'LABSA',
    nome_quimico: 'Ácido alquilbenzeno sulfônico linear',
    numero_cas: '85536-14-7',
    categoria: 'Tensoativos',
    subcategoria: 'Aniônicos',
    aparencia: 'Líquido viscoso marrom escuro',
    ph_solucao: '1.5-2.5 (puro)',
    densidade: '1.06 g/mL',
    solubilidade_agua: 'Solúvel após neutralização',
    faixa_uso_tipica: '5% - 20%',
    funcao_principal: 'Tensoativo aniônico base, detergente primário',
    sinergias: JSON.stringify(['NaOH', 'SLES', 'CDEA']),
    incompatibilidades: JSON.stringify(['Tensoativos catiônicos', 'Cálcio/Magnésio (água dura)']),
    ph_estabilidade: '7-11 (como sal)',
    restricoes_anvisa: 'Permitido em saneantes até 20%',
    nivel_toxicidade: 'medio',
    biodegradabilidade: 'Alta (>90% OCDE 301B)',
    origem: 'petroleo',
    fornecedores: JSON.stringify(['Petroquímica Suape', 'Petrobras', 'Stepan']),
    custo_min: 3.0,
    custo_max: 5.5,
    disponibilidade: 'alta',
    aplicacoes_tipicas: JSON.stringify(['Limpeza Industrial', 'Saneantes']),
    notas_tecnicas: 'Neutralizar com NaOH ou KOH antes de adicionar outros componentes. pH final 8-10. Pode causar irritação ocular.',
  },
  {
    nome_comercial: 'SLES 70%',
    nome_quimico: 'Lauril éter sulfato de sódio (2EO)',
    numero_cas: '68585-34-2',
    inci_name: 'Sodium Laureth Sulfate',
    categoria: 'Tensoativos',
    subcategoria: 'Aniônicos',
    aparencia: 'Pasta branca a amarelada',
    ph_solucao: '7.5-9.0',
    densidade: '1.04 g/mL',
    solubilidade_agua: 'Solúvel',
    faixa_uso_tipica: '5% - 25%',
    funcao_principal: 'Tensoativo primário, espumante, detergente',
    sinergias: JSON.stringify(['CDEA', 'Cloreto de sódio', 'LABSA']),
    incompatibilidades: JSON.stringify(['Tensoativos catiônicos', 'pH < 5']),
    ph_estabilidade: '6-10',
    restricoes_anvisa: 'Permitido em cosméticos e saneantes',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Alta',
    origem: 'petroleo',
    fornecedores: JSON.stringify(['Oxiteno', 'Basf', 'Stepan']),
    custo_min: 3.5,
    custo_max: 6.0,
    disponibilidade: 'alta',
    aplicacoes_tipicas: JSON.stringify(['Saneantes', 'Limpeza Industrial', 'Automotivo']),
    notas_tecnicas: 'Base de muitos detergentes e shampoos. Viscosidade controlada com NaCl (efeito salting-out).',
  },
  {
    nome_comercial: 'SLS',
    nome_quimico: 'Lauril sulfato de sódio',
    numero_cas: '151-21-3',
    inci_name: 'Sodium Lauryl Sulfate',
    categoria: 'Tensoativos',
    subcategoria: 'Aniônicos',
    aparencia: 'Pó ou pasta branca',
    ph_solucao: '7.5-9.5',
    densidade: '1.01 g/mL',
    solubilidade_agua: 'Solúvel',
    faixa_uso_tipica: '1% - 15%',
    funcao_principal: 'Tensoativo primário, espumante',
    sinergias: JSON.stringify(['CDEA', 'SLES']),
    incompatibilidades: JSON.stringify(['Catiônicos', 'pH < 5', 'Sais de cálcio']),
    ph_estabilidade: '6-10',
    restricoes_anvisa: 'Uso limitado em cosméticos leave-on',
    nivel_toxicidade: 'medio',
    biodegradabilidade: 'Alta',
    origem: 'vegetal',
    fornecedores: JSON.stringify(['Oxiteno', 'Basf']),
    custo_min: 4.0,
    custo_max: 7.0,
    disponibilidade: 'alta',
    aplicacoes_tipicas: JSON.stringify(['Saneantes', 'Limpeza Industrial']),
    notas_tecnicas: 'Mais irritante que SLES. Para formulações rinse-off. Origem vegetal (coco) disponível.',
  },
  // ─── TENSOATIVOS NÃO-IÔNICOS ─────────────────────────────────────────────
  {
    nome_comercial: 'Álcool Etoxilado 7EO',
    nome_quimico: 'Álcool graxo etoxilado (C12-C15, 7 OE)',
    numero_cas: '68439-45-2',
    categoria: 'Tensoativos',
    subcategoria: 'Não-iônicos',
    aparencia: 'Líquido incolor a amarelo pálido',
    ph_solucao: '6.0-8.0',
    densidade: '0.97 g/mL',
    solubilidade_agua: 'Solúvel',
    faixa_uso_tipica: '2% - 10%',
    funcao_principal: 'Tensoativo não-iônico, emulsificante, detergente',
    sinergias: JSON.stringify(['LABSA', 'SLES', 'DGBE']),
    incompatibilidades: JSON.stringify(['Oxidantes fortes']),
    ph_estabilidade: '3-12',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Alta',
    origem: 'petroleo',
    fornecedores: JSON.stringify(['Oxiteno', 'Basf', 'Dow']),
    custo_min: 6.0,
    custo_max: 10.0,
    disponibilidade: 'alta',
    aplicacoes_tipicas: JSON.stringify(['Limpeza Industrial', 'Automotivo', 'Tintas e Vernizes']),
    notas_tecnicas: 'Boa tolerância a água dura. Compatível com catiônicos e aniônicos. HLB ~12.',
  },
  {
    nome_comercial: 'APG (Alquil Poliglicosídeo)',
    nome_quimico: 'Alquil poliglicosídeo C8-C16',
    numero_cas: '110615-47-9',
    inci_name: 'Coco-Glucoside',
    categoria: 'Tensoativos',
    subcategoria: 'Não-iônicos',
    aparencia: 'Líquido levemente amarelado',
    ph_solucao: '11.0-12.0',
    densidade: '1.09 g/mL',
    solubilidade_agua: 'Solúvel',
    faixa_uso_tipica: '3% - 15%',
    funcao_principal: 'Tensoativo suave bio-based, co-tensoativo',
    sinergias: JSON.stringify(['Betaína de coco', 'SLES']),
    incompatibilidades: JSON.stringify(['pH muito baixo (< 3)']),
    ph_estabilidade: '4-12',
    restricoes_anvisa: 'Permitido em cosméticos e saneantes',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Muito alta (>95%)',
    origem: 'vegetal',
    certificacoes: JSON.stringify(['Ecocert', 'COSMOS', 'USDA Organic eligible', 'Biodegradável']),
    fornecedores: JSON.stringify(['Basf (Plantacare)', 'Cognis', 'Oxiteno']),
    custo_min: 12.0,
    custo_max: 22.0,
    disponibilidade: 'media',
    aplicacoes_tipicas: JSON.stringify(['Saneantes', 'Limpeza Industrial', 'Cosméticos']),
    notas_tecnicas: 'Origem 100% vegetal (coco + glucose). Certificável Ecocert. Ótimo para formulações verdes.',
  },
  {
    nome_comercial: 'Cocoamida DEA (CDEA)',
    nome_quimico: 'Cocamida dietanolamina',
    numero_cas: '68603-42-9',
    inci_name: 'Cocamide DEA',
    categoria: 'Tensoativos',
    subcategoria: 'Não-iônicos',
    aparencia: 'Pasta/líquido amarelo âmbar',
    ph_solucao: '9.0-11.0',
    densidade: '1.00 g/mL',
    solubilidade_agua: 'Solúvel em quente',
    faixa_uso_tipica: '1% - 5%',
    funcao_principal: 'Espessante, estabilizador de espuma, co-tensoativo',
    sinergias: JSON.stringify(['SLES', 'LABSA']),
    incompatibilidades: JSON.stringify(['Ácidos fortes', 'Catiônicos em excesso']),
    ph_estabilidade: '6-11',
    restricoes_anvisa: 'SCCS opinião 2012 — limitar a 1% por potencial formação de nitrosaminas',
    nivel_toxicidade: 'medio',
    biodegradabilidade: 'Moderada',
    origem: 'vegetal',
    fornecedores: JSON.stringify(['Oxiteno', 'Basf', 'Croda']),
    custo_min: 7.0,
    custo_max: 12.0,
    disponibilidade: 'alta',
    aplicacoes_tipicas: JSON.stringify(['Saneantes', 'Limpeza Industrial']),
    notas_tecnicas: 'Limitar a 1% em formulações cosméticas (risco nitrosaminas). Em limpeza industrial pode usar até 3-5%.',
  },
  {
    nome_comercial: 'Polissorbato 20',
    nome_quimico: 'PEG-20 sorbitano monolaurato',
    numero_cas: '9005-64-5',
    inci_name: 'Polysorbate 20',
    categoria: 'Tensoativos',
    subcategoria: 'Não-iônicos',
    aparencia: 'Líquido viscoso amarelo pálido',
    ph_solucao: '5.0-7.0',
    densidade: '1.10 g/mL',
    solubilidade_agua: 'Solúvel',
    faixa_uso_tipica: '0.5% - 5%',
    funcao_principal: 'Emulsificante, solubilizante de fragrâncias e óleos',
    sinergias: JSON.stringify(['Fragrâncias', 'Óleos essenciais']),
    incompatibilidades: JSON.stringify(['Fenóis', 'Taninos']),
    ph_estabilidade: '3-9',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Moderada',
    origem: 'vegetal',
    fornecedores: JSON.stringify(['Croda', 'ICI Surfactants']),
    custo_min: 18.0,
    custo_max: 35.0,
    disponibilidade: 'media',
    aplicacoes_tipicas: JSON.stringify(['Saneantes', 'Cosméticos']),
    notas_tecnicas: 'HLB ~16.7. Excelente para solubilizar fragrâncias em bases aquosas. Compatível com eletrólitos.',
  },
  {
    nome_comercial: 'NPE 9.5 (Nonilfenol Etoxilado)',
    nome_quimico: 'Nonilfenil polietilenoglicol éter (9.5 OE)',
    numero_cas: '127087-87-0',
    categoria: 'Tensoativos',
    subcategoria: 'Não-iônicos',
    aparencia: 'Líquido incolor a amarelo pálido',
    ph_solucao: '6.0-8.0',
    densidade: '1.06 g/mL',
    solubilidade_agua: 'Solúvel',
    faixa_uso_tipica: '1% - 8%',
    funcao_principal: 'Tensoativo não-iônico, emulsificante, detergente',
    sinergias: JSON.stringify(['LABSA', 'Álcool etoxilado']),
    incompatibilidades: JSON.stringify(['Oxidantes fortes']),
    ph_estabilidade: '3-12',
    restricoes_anvisa: 'Restrições em saneantes domissanitários',
    restricoes_reach: 'RESTRITO — Proibido em artigos têxteis e de couro para exportação EU (REACH SVHC)',
    nivel_toxicidade: 'alto',
    biodegradabilidade: 'Baixa (metabólito nonilfenol é disruptor endócrino)',
    origem: 'petroleo',
    certificacoes: JSON.stringify([]),
    fornecedores: JSON.stringify(['Oxiteno']),
    custo_min: 5.0,
    custo_max: 8.0,
    disponibilidade: 'media',
    aplicacoes_tipicas: JSON.stringify(['Limpeza Industrial']),
    notas_tecnicas: 'ATENÇÃO: Disruptor endócrino. Proibido na EU (REACH). Substituir por álcoois etoxilados ou APG.',
  },
  // ─── ESPESSANTES / REOLÓGICOS ─────────────────────────────────────────────
  {
    nome_comercial: 'Goma Xantana',
    nome_quimico: 'Xantano (polissacarídeo bacteriano)',
    numero_cas: '11138-66-2',
    inci_name: 'Xanthan Gum',
    categoria: 'Aditivos Funcionais',
    subcategoria: 'Espessantes / reológicos',
    aparencia: 'Pó branco a creme',
    ph_solucao: '6.0-8.0 (1%)',
    densidade: '1.6 g/cm³ (pó)',
    solubilidade_agua: 'Dispersível/solúvel com agitação',
    faixa_uso_tipica: '0.1% - 1.0%',
    funcao_principal: 'Espessante, estabilizante de suspensões, reológico',
    sinergias: JSON.stringify(['Goma guar', 'NaCl']),
    incompatibilidades: JSON.stringify(['Surfactantes catiônicos em excesso', 'Ácido bórico']),
    ph_estabilidade: '4-10',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Alta',
    origem: 'bio-sintetico',
    certificacoes: JSON.stringify(['GRAS (FDA)', 'Kosher', 'Halal']),
    fornecedores: JSON.stringify(['CP Kelco', 'Jungbunzlauer', 'Galena']),
    custo_min: 25.0,
    custo_max: 55.0,
    disponibilidade: 'media',
    aplicacoes_tipicas: JSON.stringify(['Limpeza Industrial', 'Saneantes', 'Tintas e Vernizes']),
    notas_tecnicas: 'Dispersar em água fria com agitação intensa. Hidrata em 30-60 min. Boa tolerância a eletrólitos.',
  },
  {
    nome_comercial: 'Carbopol 940',
    nome_quimico: 'Ácido poliacrílico reticulado',
    numero_cas: '9003-01-4',
    inci_name: 'Carbomer',
    categoria: 'Aditivos Funcionais',
    subcategoria: 'Espessantes / reológicos',
    aparencia: 'Pó branco fluente',
    ph_solucao: '2.5-3.5 (0.5%)',
    densidade: '1.41 g/cm³ (pó)',
    solubilidade_agua: 'Dispersível, espessa com neutralização',
    faixa_uso_tipica: '0.1% - 1.5%',
    funcao_principal: 'Espessante, geleificante, estabilizante de emulsões',
    sinergias: JSON.stringify(['TEA', 'NaOH', 'MEA']),
    incompatibilidades: JSON.stringify(['Eletrólitos (NaCl, MgCl2)', 'pH < 5 ou > 11', 'Catiônicos fortes']),
    ph_estabilidade: '5-11 (após neutralização)',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Baixa (sintético)',
    origem: 'petroleo',
    fornecedores: JSON.stringify(['Lubrizol', 'Galena', 'Dow']),
    custo_min: 35.0,
    custo_max: 80.0,
    disponibilidade: 'media',
    aplicacoes_tipicas: JSON.stringify(['Saneantes', 'Limpeza Industrial', 'Cosméticos']),
    notas_tecnicas: 'Dispersar em água antes de outros ingredientes. Neutralizar com TEA ou NaOH para gelificar. Sensível a eletrólitos.',
  },
  {
    nome_comercial: 'HEC (Hidroxietilcelulose)',
    nome_quimico: 'Celulose 2-hidroxietil éter',
    numero_cas: '9004-62-0',
    inci_name: 'Hydroxyethylcellulose',
    categoria: 'Aditivos Funcionais',
    subcategoria: 'Espessantes / reológicos',
    aparencia: 'Pó branco a creme',
    ph_solucao: '6.0-8.0',
    densidade: '0.5 g/cm³ (pó)',
    solubilidade_agua: 'Solúvel com agitação',
    faixa_uso_tipica: '0.5% - 3.0%',
    funcao_principal: 'Espessante, protetor coloidal',
    sinergias: JSON.stringify(['Água', 'Tensoativos']),
    incompatibilidades: JSON.stringify(['Oxidantes fortes', 'Sais de boro']),
    ph_estabilidade: '3-11',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Alta',
    origem: 'vegetal',
    fornecedores: JSON.stringify(['Ashland', 'Galena', 'Dow']),
    custo_min: 30.0,
    custo_max: 65.0,
    disponibilidade: 'media',
    aplicacoes_tipicas: JSON.stringify(['Tintas e Vernizes', 'Saneantes', 'Limpeza Industrial']),
    notas_tecnicas: 'Tolerante a eletrólitos (vantagem sobre Carbopol). Dispersar a seco antes de umedecer.',
  },
  // ─── SEQUESTRANTES / QUELANTES ────────────────────────────────────────────
  {
    nome_comercial: 'EDTA Tetrassódico',
    nome_quimico: 'Ácido etilenodiaminotetraacético sal tetrassódico',
    numero_cas: '64-02-8',
    inci_name: 'Tetrasodium EDTA',
    categoria: 'Aditivos Funcionais',
    subcategoria: 'Sequestrantes / quelantes',
    aparencia: 'Pó branco cristalino',
    ph_solucao: '10.5-11.5',
    densidade: '0.85 g/cm³',
    solubilidade_agua: 'Solúvel (38 g/100mL)',
    faixa_uso_tipica: '0.1% - 1.0%',
    funcao_principal: 'Sequestrante de íons metálicos, quelante',
    sinergias: JSON.stringify(['LABSA', 'LAS', 'NaOH']),
    incompatibilidades: JSON.stringify(['pH < 3']),
    ph_estabilidade: '4-13',
    restricoes_anvisa: 'Uso permitido em saneantes',
    restricoes_reach: 'Monitorado — persistente no ambiente',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Baixa (persistente)',
    origem: 'petroleo',
    fornecedores: JSON.stringify(['BASF', 'Merck', 'Galena']),
    custo_min: 8.0,
    custo_max: 15.0,
    disponibilidade: 'alta',
    aplicacoes_tipicas: JSON.stringify(['Limpeza Industrial', 'Saneantes']),
    notas_tecnicas: 'Melhora desempenho em água dura. Persistente no ambiente — considerar GLDA ou MGDA como alternativa verde.',
  },
  {
    nome_comercial: 'GLDA Tetrassódico',
    nome_quimico: 'Ácido glutâmico N,N-diacético tetrassódico',
    numero_cas: '51981-21-6',
    inci_name: 'Tetrasodium Glutamate Diacetate',
    categoria: 'Aditivos Funcionais',
    subcategoria: 'Sequestrantes / quelantes',
    aparencia: 'Líquido incolor a levemente amarelo',
    ph_solucao: '11.0-12.0',
    densidade: '1.27 g/mL',
    solubilidade_agua: 'Miscível',
    faixa_uso_tipica: '0.5% - 3.0%',
    funcao_principal: 'Sequestrante biodegradável, alternativa ao EDTA',
    sinergias: JSON.stringify(['Tensoativos', 'Álcalis']),
    incompatibilidades: JSON.stringify(['pH < 2']),
    ph_estabilidade: '4-13',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Alta (>60% OCDE 301B)',
    origem: 'bio-sintetico',
    certificacoes: JSON.stringify(['Ecocert elegível', 'COSMOS aprovado']),
    fornecedores: JSON.stringify(['BASF (Dissolvine GL)', 'AkzoNobel']),
    custo_min: 18.0,
    custo_max: 35.0,
    disponibilidade: 'media',
    aplicacoes_tipicas: JSON.stringify(['Limpeza Industrial', 'Saneantes']),
    notas_tecnicas: 'Substituto biodegradável do EDTA. Origem amino-ácido (ácido glutâmico). Preferencial para formulações verdes.',
  },
  {
    nome_comercial: 'Ácido Cítrico',
    nome_quimico: 'Ácido 2-hidroxi-1,2,3-propanocarboxílico',
    numero_cas: '77-92-9',
    inci_name: 'Citric Acid',
    categoria: 'Aditivos Funcionais',
    subcategoria: 'Sequestrantes / quelantes',
    aparencia: 'Pó/cristais brancos',
    ph_solucao: '2.0-2.5 (10%)',
    densidade: '1.665 g/cm³',
    solubilidade_agua: 'Solúvel (592 g/L)',
    faixa_uso_tipica: '0.5% - 5.0%',
    funcao_principal: 'Acidulante, quelante, tamponante, removedor de calcário',
    sinergias: JSON.stringify(['Ácido glucônico', 'GLDA']),
    incompatibilidades: JSON.stringify(['Bases fortes (reação exotérmica)', 'Carbonatos']),
    ph_estabilidade: '2-6',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Muito alta',
    origem: 'bio-sintetico',
    certificacoes: JSON.stringify(['GRAS (FDA)', 'Ecocert', 'COSMOS']),
    fornecedores: JSON.stringify(['Citroleo', 'Jungbunzlauer', 'ADM']),
    custo_min: 4.0,
    custo_max: 8.0,
    disponibilidade: 'alta',
    aplicacoes_tipicas: JSON.stringify(['Limpeza Industrial', 'Saneantes', 'Automotivo']),
    notas_tecnicas: 'Excelente para descalcificantes e limpadores ácidos. Origem fermentativa de milho/cana.',
  },
  // ─── NEUTRALIZANTES E TAMPONANTES ────────────────────────────────────────
  {
    nome_comercial: 'NaOH (Soda Cáustica)',
    nome_quimico: 'Hidróxido de sódio',
    numero_cas: '1310-73-2',
    categoria: 'Neutralizantes e Tamponantes',
    subcategoria: 'Alcalinizante',
    aparencia: 'Pérolas/escamas brancas ou solução límpida',
    ph_solucao: '13.5-14.0 (1%)',
    densidade: '2.13 g/cm³ (sólido), 1.53 g/mL (50%)',
    solubilidade_agua: 'Muito solúvel (111 g/100mL)',
    faixa_uso_tipica: '0.5% - 10% (solução 50%)',
    funcao_principal: 'Alcalinizante, neutralizante de ácidos, saponificante',
    sinergias: JSON.stringify(['LABSA', 'Carbopol']),
    incompatibilidades: JSON.stringify(['Ácidos (reação violenta)', 'Alumínio', 'Zinco', 'Aminas']),
    ph_estabilidade: '9-14',
    nivel_toxicidade: 'alto',
    biodegradabilidade: 'N/A (inorgânico)',
    origem: 'mineral',
    fornecedores: JSON.stringify(['Dow Chemical', 'Unipar', 'Solvay']),
    custo_min: 1.5,
    custo_max: 3.5,
    disponibilidade: 'alta',
    aplicacoes_tipicas: JSON.stringify(['Limpeza Industrial', 'Saneantes', 'Tintas e Vernizes']),
    notas_tecnicas: 'Corrosivo — EPI completo. Reação exotérmica com água. Adicionar sempre ao líquido, nunca o contrário.',
  },
  {
    nome_comercial: 'KOH (Potassa Cáustica)',
    nome_quimico: 'Hidróxido de potássio',
    numero_cas: '1310-58-3',
    categoria: 'Neutralizantes e Tamponantes',
    subcategoria: 'Alcalinizante',
    aparencia: 'Pérolas/escamas brancas',
    ph_solucao: '13.5-14.0 (1%)',
    densidade: '2.04 g/cm³',
    solubilidade_agua: 'Muito solúvel (121 g/100mL)',
    faixa_uso_tipica: '0.5% - 8%',
    funcao_principal: 'Alcalinizante, neutralizante, saponificante',
    sinergias: JSON.stringify(['Tensoativos aniônicos']),
    incompatibilidades: JSON.stringify(['Ácidos', 'Metais anfóteros']),
    ph_estabilidade: '9-14',
    nivel_toxicidade: 'alto',
    biodegradabilidade: 'N/A (inorgânico)',
    origem: 'mineral',
    fornecedores: JSON.stringify(['Dow', 'Unipar']),
    custo_min: 3.0,
    custo_max: 6.0,
    disponibilidade: 'alta',
    aplicacoes_tipicas: JSON.stringify(['Limpeza Industrial', 'Biossolventes']),
    notas_tecnicas: 'Preferível ao NaOH quando sal de potássio é desejado (menor tendência a formar precipitados).',
  },
  {
    nome_comercial: 'MEA (Monoetanolamina)',
    nome_quimico: '2-Aminoetanol',
    numero_cas: '141-43-5',
    categoria: 'Neutralizantes e Tamponantes',
    subcategoria: 'Alcalinizante orgânico',
    aparencia: 'Líquido viscoso incolor, odor amoniacal',
    ph_solucao: '11.0-12.0',
    densidade: '1.012 g/mL',
    solubilidade_agua: 'Miscível',
    faixa_uso_tipica: '0.5% - 5%',
    funcao_principal: 'Alcalinizante orgânico, neutralizante, absorvente de CO2',
    sinergias: JSON.stringify(['LABSA', 'Carbopol']),
    incompatibilidades: JSON.stringify(['Ácidos minerais fortes', 'Oxidantes', 'Cobre']),
    ph_estabilidade: '8-12',
    nivel_toxicidade: 'medio',
    biodegradabilidade: 'Alta',
    origem: 'petroleo',
    fornecedores: JSON.stringify(['Dow Chemical', 'BASF']),
    custo_min: 5.0,
    custo_max: 9.0,
    disponibilidade: 'alta',
    aplicacoes_tipicas: JSON.stringify(['Limpeza Industrial', 'Tintas e Vernizes']),
    notas_tecnicas: 'Odor típico de amina. Usar em espaços ventilados. Menos corrosivo que NaOH.',
  },
  {
    nome_comercial: 'Ácido Clorídrico 36%',
    nome_quimico: 'Ácido clorídrico',
    numero_cas: '7647-01-0',
    categoria: 'Neutralizantes e Tamponantes',
    subcategoria: 'Acidulante mineral',
    aparencia: 'Líquido incolor a levemente amarelado, fumos brancos',
    ph_solucao: '< 1.0',
    densidade: '1.18 g/mL (36%)',
    solubilidade_agua: 'Miscível',
    faixa_uso_tipica: '1% - 15%',
    funcao_principal: 'Acidulante, descalcificante, removedor de ferrugem/óxidos',
    sinergias: JSON.stringify(['Inibidores de corrosão', 'Ácido fosfórico']),
    incompatibilidades: JSON.stringify(['Bases', 'Metais (reação com H2 gasoso)', 'Oxidantes']),
    ph_estabilidade: '1-5',
    nivel_toxicidade: 'alto',
    biodegradabilidade: 'N/A (inorgânico)',
    origem: 'mineral',
    fornecedores: JSON.stringify(['Unipar', 'Dow', 'Solvay']),
    custo_min: 1.0,
    custo_max: 3.0,
    disponibilidade: 'alta',
    aplicacoes_tipicas: JSON.stringify(['Limpeza Industrial', 'Automotivo']),
    notas_tecnicas: 'Corrosivo/tóxico — vapores de HCl irritantes. EPI completo. Adicionar ao produto NUNCA o contrário.',
  },
  // ─── CONSERVANTES / BIOCIDAS ──────────────────────────────────────────────
  {
    nome_comercial: 'Benzalcônio Cloreto 50%',
    nome_quimico: 'Cloreto de alquildimetilbenzilamônio',
    numero_cas: '8001-54-5',
    inci_name: 'Benzalkonium Chloride',
    categoria: 'Aditivos Funcionais',
    subcategoria: 'Conservantes / biocidas',
    aparencia: 'Líquido claro a amarelado',
    ph_solucao: '6.0-8.0',
    densidade: '0.98 g/mL',
    solubilidade_agua: 'Solúvel',
    faixa_uso_tipica: '0.05% - 1.0%',
    funcao_principal: 'Biocida, conservante, tensoativo catiônico',
    sinergias: JSON.stringify(['Álcool etílico', 'EDTA']),
    incompatibilidades: JSON.stringify(['Aniônicos (LABSA, SLES — precipita)', 'pH > 12']),
    ph_estabilidade: '4-10',
    restricoes_anvisa: 'Uso regulamentado em saneantes e cosméticos',
    nivel_toxicidade: 'medio',
    biodegradabilidade: 'Moderada',
    origem: 'petroleo',
    fornecedores: JSON.stringify(['Galena', 'Lonza', 'Solvay']),
    custo_min: 8.0,
    custo_max: 18.0,
    disponibilidade: 'alta',
    aplicacoes_tipicas: JSON.stringify(['Saneantes', 'Automotivo', 'Limpeza Industrial']),
    notas_tecnicas: 'CATIÔNICO — incompatível com aniônicos. Boa ação bactericida e fungicida. Usado em desinfetantes.',
  },
  {
    nome_comercial: 'Ácido Benzoico',
    nome_quimico: 'Ácido benzeno-1-carboxílico',
    numero_cas: '65-85-0',
    inci_name: 'Benzoic Acid',
    categoria: 'Aditivos Funcionais',
    subcategoria: 'Conservantes / biocidas',
    aparencia: 'Pó branco cristalino',
    ph_solucao: '2.8 (saturado)',
    densidade: '1.32 g/cm³',
    solubilidade_agua: 'Pouco solúvel (3.4 g/L a 25°C) — melhora com pH > 5',
    faixa_uso_tipica: '0.05% - 0.5%',
    funcao_principal: 'Conservante antimicrobiano (leveduras, bolores)',
    sinergias: JSON.stringify(['Ácido sórbico', 'EDTA']),
    incompatibilidades: JSON.stringify(['pH > 7 (perde eficácia)', 'Bases']),
    ph_estabilidade: '3-5',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Alta',
    origem: 'petroleo',
    certificacoes: JSON.stringify(['GRAS (FDA)', 'INS 210']),
    fornecedores: JSON.stringify(['Galena', 'Merck', 'Vennex']),
    custo_min: 6.0,
    custo_max: 12.0,
    disponibilidade: 'alta',
    aplicacoes_tipicas: JSON.stringify(['Saneantes', 'Cosméticos']),
    notas_tecnicas: 'Ativo apenas em pH ácido (< 5). Solubilizar em álcool antes de adicionar à fase aquosa.',
  },
  // ─── INIBIDORES DE CORROSÃO ───────────────────────────────────────────────
  {
    nome_comercial: 'Benzotriazol (BTA)',
    nome_quimico: '1H-Benzotriazol',
    numero_cas: '95-14-7',
    categoria: 'Aditivos Funcionais',
    subcategoria: 'Inibidores de corrosão',
    aparencia: 'Pó branco a levemente amarelado',
    ph_solucao: '5.0-7.0',
    densidade: '1.36 g/cm³',
    solubilidade_agua: 'Moderada (20 g/L)',
    faixa_uso_tipica: '0.1% - 1.0%',
    funcao_principal: 'Inibidor de corrosão para cobre e ligas não-ferrosas',
    sinergias: JSON.stringify(['Molibidata de sódio', 'Silicato de sódio']),
    incompatibilidades: JSON.stringify(['Oxidantes fortes', 'Ácidos concentrados']),
    ph_estabilidade: '5-12',
    restricoes_reach: 'SVHC candidato — verificar restrições',
    nivel_toxicidade: 'medio',
    biodegradabilidade: 'Baixa (persistente)',
    origem: 'petroleo',
    fornecedores: JSON.stringify(['Lanxess', 'BASF', 'Galena']),
    custo_min: 25.0,
    custo_max: 60.0,
    disponibilidade: 'media',
    aplicacoes_tipicas: JSON.stringify(['Limpeza Industrial', 'Automotivo']),
    notas_tecnicas: 'Excelente para proteção de cobre, latão e bronze. Forma filme passivador na superfície.',
  },
  {
    nome_comercial: 'Silicato de Sódio',
    nome_quimico: 'Metassilicato de sódio',
    numero_cas: '6834-92-0',
    categoria: 'Aditivos Funcionais',
    subcategoria: 'Inibidores de corrosão',
    aparencia: 'Pó branco ou solução viscosa',
    ph_solucao: '11.0-13.0',
    densidade: '1.35-1.50 g/mL',
    solubilidade_agua: 'Solúvel',
    faixa_uso_tipica: '1% - 5%',
    funcao_principal: 'Inibidor de corrosão para aço, alcalinizante, sequestrante',
    sinergias: JSON.stringify(['EDTA', 'NaOH', 'Tensoativos aniônicos']),
    incompatibilidades: JSON.stringify(['Ácidos (precipita SiO2)', 'Cálcio/magnésio (precipita)']),
    ph_estabilidade: '10-14',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'N/A (inorgânico)',
    origem: 'mineral',
    fornecedores: JSON.stringify(['PQ Corporation', 'Elkem', 'Quimibrás']),
    custo_min: 2.0,
    custo_max: 6.0,
    disponibilidade: 'alta',
    aplicacoes_tipicas: JSON.stringify(['Limpeza Industrial']),
    notas_tecnicas: 'Tamponante alcalino. Passivador de aço. Pode reduzir eficácia de tensoativos por precipitação de cálcio.',
  },
  // ─── RESINAS E POLÍMEROS ──────────────────────────────────────────────────
  {
    nome_comercial: 'Resina Alquídica 60% Mineral Spirit',
    nome_quimico: 'Resina alquídica de média cadeia (60% NV em solvente alifático)',
    numero_cas: '8050-26-8',
    categoria: 'Resinas e Polímeros',
    subcategoria: 'Resinas alquídicas',
    aparencia: 'Líquido viscoso âmbar',
    ph_solucao: 'N/A (sistema solvente)',
    densidade: '1.02-1.08 g/mL',
    solubilidade_agua: 'Insolúvel',
    faixa_uso_tipica: '30% - 70%',
    funcao_principal: 'Formadora de filme, ligante principal em tintas alquídicas',
    sinergias: JSON.stringify(['Secantes (octoato de cobalto, manganês)', 'Mineral spirit']),
    incompatibilidades: JSON.stringify(['Água', 'Bases fortes (saponificação)']),
    ph_estabilidade: 'N/A',
    nivel_toxicidade: 'medio',
    biodegradabilidade: 'Baixa',
    origem: 'petroleo',
    fornecedores: JSON.stringify(['Nuplex', 'Allnex', 'Iquine']),
    custo_min: 8.0,
    custo_max: 18.0,
    disponibilidade: 'alta',
    aplicacoes_tipicas: JSON.stringify(['Tintas e Vernizes']),
    notas_tecnicas: 'Cura oxidativa — requer secantes e tempo de secagem ao ar. Ponto de fulgor do solvente ~38°C.',
  },
  {
    nome_comercial: 'Resina Acrílica Aquosa 45%',
    nome_quimico: 'Dispersão aquosa de copolímero acrílico (45% sólidos)',
    numero_cas: '9003-49-0',
    categoria: 'Resinas e Polímeros',
    subcategoria: 'Resinas acrílicas',
    aparencia: 'Emulsão branca leitosa',
    ph_solucao: '7.5-9.5',
    densidade: '1.05 g/mL',
    solubilidade_agua: 'Dispersão aquosa',
    faixa_uso_tipica: '30% - 60%',
    funcao_principal: 'Ligante aquoso, formador de filme, adesivo',
    sinergias: JSON.stringify(['Coalescentes (DGBE)', 'Espessantes HEC']),
    incompatibilidades: JSON.stringify(['pH < 5 (coagulação)', 'Eletrólitos em excesso', 'Solventes aromáticos']),
    ph_estabilidade: '6-10',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Baixa (polímero)',
    origem: 'petroleo',
    fornecedores: JSON.stringify(['Basf', 'Dow', 'Nuplex']),
    custo_min: 7.0,
    custo_max: 16.0,
    disponibilidade: 'alta',
    aplicacoes_tipicas: JSON.stringify(['Tintas e Vernizes']),
    notas_tecnicas: 'Base aquosa — baixo VOC. Coalescente (DGBE, Texanol) necessário abaixo da temperatura de mínima formação de filme (MFT).',
  },
  {
    nome_comercial: 'Resina Epóxi Bisfenol A (EEW 188)',
    nome_quimico: 'Resina epóxi baseada em Bisfenol A diglicidil éter',
    numero_cas: '25068-38-6',
    categoria: 'Resinas e Polímeros',
    subcategoria: 'Resinas epóxi',
    aparencia: 'Líquido viscoso a sólido transparente âmbar',
    densidade: '1.17 g/mL',
    solubilidade_agua: 'Insolúvel',
    faixa_uso_tipica: '40% - 70% (parte A)',
    funcao_principal: 'Ligante de alta performance, anticorrosivo, revestimento industrial',
    sinergias: JSON.stringify(['Endurecedores poliamina', 'Endurecedores poliamida']),
    incompatibilidades: JSON.stringify(['Ácidos fortes', 'Bases fortes', 'Não misturar sem endurecedor']),
    ph_estabilidade: 'N/A',
    restricoes_reach: 'Bisfenol A é SVHC — verificar regulação',
    nivel_toxicidade: 'medio',
    biodegradabilidade: 'Muito baixa',
    origem: 'petroleo',
    fornecedores: JSON.stringify(['Olin (D.E.R.)', 'Momentive', 'Huntsman']),
    custo_min: 18.0,
    custo_max: 40.0,
    disponibilidade: 'alta',
    aplicacoes_tipicas: JSON.stringify(['Tintas e Vernizes']),
    notas_tecnicas: 'Sistema bicomponente (resina + endurecedor). Sensibilizante dérmico — EPI rigoroso. Alta resistência química.',
  },
  // ─── MATÉRIAS-PRIMAS SUSTENTÁVEIS ─────────────────────────────────────────
  {
    nome_comercial: 'Betaína de Coco',
    nome_quimico: 'Cocamidopropil betaína',
    numero_cas: '61789-40-0',
    inci_name: 'Cocamidopropyl Betaine',
    categoria: 'Tensoativos',
    subcategoria: 'Anfóteros / Zwitteriônicos',
    aparencia: 'Líquido levemente amarelado',
    ph_solucao: '4.5-6.5',
    densidade: '1.05 g/mL',
    solubilidade_agua: 'Solúvel',
    faixa_uso_tipica: '3% - 15%',
    funcao_principal: 'Tensoativo anfótero suave, co-surfactante, estabilizador de espuma',
    sinergias: JSON.stringify(['SLES', 'APG', 'LABSA']),
    incompatibilidades: JSON.stringify(['pH extremo (< 3 ou > 12 prolongado)']),
    ph_estabilidade: '3-12',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Alta',
    origem: 'vegetal',
    certificacoes: JSON.stringify(['Ecocert elegível', 'COSMOS aprovado']),
    fornecedores: JSON.stringify(['Oxiteno', 'Evonik', 'Solvay']),
    custo_min: 10.0,
    custo_max: 20.0,
    disponibilidade: 'alta',
    aplicacoes_tipicas: JSON.stringify(['Saneantes', 'Cosméticos', 'Limpeza Industrial']),
    notas_tecnicas: 'Compatível com aniônicos e catiônicos. Reduz irritação ocular em formulações com SLS/SLES.',
  },
  {
    nome_comercial: 'Glicerina USP',
    nome_quimico: 'Glicerol',
    numero_cas: '56-81-5',
    inci_name: 'Glycerin',
    categoria: 'Matérias-primas Sustentáveis',
    subcategoria: 'Origem vegetal / bio-based',
    aparencia: 'Líquido viscoso incolor, sem odor',
    ph_solucao: '7.0',
    densidade: '1.261 g/mL',
    solubilidade_agua: 'Miscível',
    faixa_uso_tipica: '1% - 20%',
    funcao_principal: 'Umectante, solvente, plastificante, co-formulante',
    sinergias: JSON.stringify(['Propilenoglicol', 'Álcool etílico']),
    incompatibilidades: JSON.stringify(['Oxidantes fortes', 'Ácido crômico']),
    ph_estabilidade: '1-14',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Alta',
    origem: 'vegetal',
    certificacoes: JSON.stringify(['USP/NF', 'GRAS', 'Kosher', 'Halal', 'Bio-based']),
    fornecedores: JSON.stringify(['Cargill', 'ADM', 'P&G Chemicals']),
    custo_min: 3.0,
    custo_max: 7.0,
    disponibilidade: 'alta',
    aplicacoes_tipicas: JSON.stringify(['Saneantes', 'Cosméticos', 'Biossolventes']),
    notas_tecnicas: 'Co-produto da produção de biodiesel (soja/cana). Baixo custo por ser subproduto. Umectante e plasticizante.',
  },
  {
    nome_comercial: 'Ácido Lático 80%',
    nome_quimico: 'Ácido 2-hidroxipropanoico',
    numero_cas: '50-21-5',
    inci_name: 'Lactic Acid',
    categoria: 'Matérias-primas Sustentáveis',
    subcategoria: 'Origem vegetal / bio-based',
    aparencia: 'Líquido viscoso incolor a levemente amarelado',
    ph_solucao: '1.5-2.5',
    densidade: '1.21 g/mL',
    solubilidade_agua: 'Miscível',
    faixa_uso_tipica: '0.1% - 5%',
    funcao_principal: 'Acidulante bio-based, ajustador de pH, quelante suave',
    sinergias: JSON.stringify(['Ácido cítrico', 'Gluconato de sódio']),
    incompatibilidades: JSON.stringify(['Bases fortes']),
    ph_estabilidade: '2-7',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Muito alta',
    origem: 'vegetal',
    certificacoes: JSON.stringify(['GRAS (FDA)', 'Ecocert', 'COSMOS', 'Bio-based']),
    fornecedores: JSON.stringify(['Corbion', 'Galactic', 'ADM']),
    custo_min: 5.0,
    custo_max: 12.0,
    disponibilidade: 'media',
    aplicacoes_tipicas: JSON.stringify(['Saneantes', 'Cosméticos', 'Limpeza Industrial']),
    notas_tecnicas: 'Origem fermentativa (milho, cana). Certificável COSMOS. Excelente para claims bio/natural.',
  },
  {
    nome_comercial: 'Propilenoglicol Vegetal',
    nome_quimico: 'Propano-1,2-diol',
    numero_cas: '57-55-6',
    inci_name: 'Propylene Glycol',
    categoria: 'Matérias-primas Sustentáveis',
    subcategoria: 'Origem vegetal / bio-based',
    aparencia: 'Líquido viscoso incolor, quase inodoro',
    ph_solucao: '7.0',
    densidade: '1.036 g/mL',
    solubilidade_agua: 'Miscível',
    faixa_uso_tipica: '2% - 20%',
    funcao_principal: 'Co-solvente, umectante, depressante de ponto de congelamento',
    sinergias: JSON.stringify(['Glicerina', 'Álcool etílico']),
    incompatibilidades: JSON.stringify(['Oxidantes fortes']),
    ph_estabilidade: '1-14',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Alta',
    origem: 'vegetal',
    certificacoes: JSON.stringify(['Bio-based (USDA)', 'GRAS']),
    fornecedores: JSON.stringify(['Dow (Susterra)', 'ADM']),
    custo_min: 6.0,
    custo_max: 14.0,
    disponibilidade: 'media',
    aplicacoes_tipicas: JSON.stringify(['Saneantes', 'Cosméticos', 'Biossolventes']),
    notas_tecnicas: 'Versão bio-based disponível (origem milho). Substituição sustentável ao PG petroquímico.',
  },
  // ─── MATÉRIAS RESTRITAS / REGULADAS ──────────────────────────────────────
  {
    nome_comercial: 'Metanol',
    nome_quimico: 'Metanol (álcool metílico)',
    numero_cas: '67-56-1',
    categoria: 'Matérias-primas Restritas / Reguladas',
    subcategoria: 'Solventes restritos',
    aparencia: 'Líquido incolor, odor alcoólico',
    ph_solucao: '7.0',
    densidade: '0.791 g/mL',
    solubilidade_agua: 'Miscível',
    faixa_uso_tipica: 'RESTRITO',
    funcao_principal: 'Solvente (USO RESTRITO)',
    sinergias: JSON.stringify([]),
    incompatibilidades: JSON.stringify(['Oxidantes', 'Bases']),
    ph_estabilidade: '1-14',
    restricoes_anvisa: 'PROIBIDO em saneantes domissanitários e cosméticos',
    restricoes_reach: 'Substância CMR Cat 1B',
    nivel_toxicidade: 'alto',
    biodegradabilidade: 'Alta',
    origem: 'petroleo',
    fornecedores: JSON.stringify([]),
    custo_min: 2.0,
    custo_max: 4.0,
    disponibilidade: 'baixa',
    aplicacoes_tipicas: JSON.stringify(['Limpeza Industrial (uso industrial controlado)']),
    notas_tecnicas: 'TÓXICO — neurotóxico. Causa cegueira e morte por ingestão. USO RESTRITO a aplicações industriais com controle rigoroso.',
  },
  {
    nome_comercial: 'Tolueno',
    nome_quimico: 'Metilbenzeno',
    numero_cas: '108-88-3',
    categoria: 'Matérias-primas Restritas / Reguladas',
    subcategoria: 'Solventes restritos',
    aparencia: 'Líquido incolor, odor aromático',
    ph_solucao: '7.0',
    densidade: '0.867 g/mL',
    solubilidade_agua: 'Praticamente insolúvel',
    faixa_uso_tipica: 'RESTRITO',
    funcao_principal: 'Solvente aromático (USO RESTRITO)',
    sinergias: JSON.stringify(['Acetona', 'MEK']),
    incompatibilidades: JSON.stringify(['Oxidantes fortes']),
    ph_estabilidade: 'N/A',
    restricoes_anvisa: 'Proibido em cosméticos e saneantes domissanitários',
    restricoes_reach: 'Substância CMR — reprotóxico Cat 2',
    nivel_toxicidade: 'alto',
    biodegradabilidade: 'Moderada',
    origem: 'petroleo',
    notas_tecnicas: 'Alto VOC, CMR, neurotóxico. Substituir por D-Limoneno, DGBE ou ésteres de baixo VOC.',
    disponibilidade: 'media',
    aplicacoes_tipicas: JSON.stringify(['Tintas e Vernizes (industrial)']),
  },
  {
    nome_comercial: 'MIT (Metilisotiazolinona)',
    nome_quimico: '2-Metil-4-isotiazolin-3-ona',
    numero_cas: '2682-20-4',
    inci_name: 'Methylisothiazolinone',
    categoria: 'Matérias-primas Restritas / Reguladas',
    subcategoria: 'Conservantes restritos',
    aparencia: 'Solução aquosa amarelada',
    ph_solucao: '3.0-5.0',
    faixa_uso_tipica: 'RESTRITO — máx 0.0015% (rinse-off)',
    funcao_principal: 'Conservante biocida (uso severamente restrito)',
    sinergias: JSON.stringify(['CMIT']),
    incompatibilidades: JSON.stringify(['Agentes redutores', 'Sulfitos']),
    ph_estabilidade: '3-8',
    restricoes_anvisa: 'Proibido em cosméticos leave-on; máx 0.0015% rinse-off',
    restricoes_reach: 'Classificado como sensibilizante de pele Cat 1A',
    nivel_toxicidade: 'alto',
    biodegradabilidade: 'Alta',
    origem: 'petroleo',
    notas_tecnicas: 'RESTRITO — forte alergênico cutâneo. Epidemia de alergias na EU 2013-2018. Substituir por Kathon CG (CMIT/MIT) em concentrações menores ou por conservantes alternativos.',
    disponibilidade: 'media',
    aplicacoes_tipicas: JSON.stringify(['Limpeza Industrial (uso controlado)']),
  },
  // ─── ANTIESPUMANTES / DISPERSANTES ───────────────────────────────────────
  {
    nome_comercial: 'Antiespumante de Silicone',
    nome_quimico: 'Polidimetilsiloxano (PDMS)',
    numero_cas: '63148-62-9',
    categoria: 'Aditivos Funcionais',
    subcategoria: 'Antiespumantes',
    aparencia: 'Líquido/emulsão branca',
    ph_solucao: '6.0-8.0',
    densidade: '1.00-1.03 g/mL',
    solubilidade_agua: 'Dispersível (emulsão)',
    faixa_uso_tipica: '0.01% - 0.5%',
    funcao_principal: 'Antiespumante em sistemas aquosos e de solvente',
    sinergias: JSON.stringify(['Sistemas de alta espuma']),
    incompatibilidades: JSON.stringify(['Sistemas de silicone para tintas (pode causar cratering)']),
    ph_estabilidade: '2-12',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Baixa',
    origem: 'petroleo',
    fornecedores: JSON.stringify(['Dow Corning', 'Momentive', 'BYK']),
    custo_min: 15.0,
    custo_max: 40.0,
    disponibilidade: 'media',
    aplicacoes_tipicas: JSON.stringify(['Limpeza Industrial', 'Tintas e Vernizes']),
    notas_tecnicas: 'Usar no mínimo necessário. Em tintas, pode causar cratering se em excesso. Adicionar no final do processo.',
  },
  {
    nome_comercial: 'CMC (Carboximetilcelulose Sódica)',
    nome_quimico: 'Celulose carboximetil éter sal de sódio',
    numero_cas: '9004-32-4',
    inci_name: 'Cellulose Gum',
    categoria: 'Aditivos Funcionais',
    subcategoria: 'Espessantes / reológicos',
    aparencia: 'Pó branco a creme',
    ph_solucao: '6.5-8.0',
    densidade: '0.5 g/cm³ (pó)',
    solubilidade_agua: 'Dispersível/solúvel',
    faixa_uso_tipica: '0.5% - 3.0%',
    funcao_principal: 'Espessante, estabilizante, protetor coloidal',
    sinergias: JSON.stringify(['HEC', 'Goma xantana']),
    incompatibilidades: JSON.stringify(['Sais de ferro e chumbo', 'pH < 3']),
    ph_estabilidade: '4-10',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Alta',
    origem: 'vegetal',
    fornecedores: JSON.stringify(['Ashland', 'CP Kelco', 'Dow']),
    custo_min: 12.0,
    custo_max: 30.0,
    disponibilidade: 'alta',
    aplicacoes_tipicas: JSON.stringify(['Tintas e Vernizes', 'Saneantes']),
    notas_tecnicas: 'Viscosidade depende da temperatura — reduz a quente. Boa em formulações alcalinas.',
  },
  // ─── BIOSSOLVENTES E BIOLUBRIFICANTES ────────────────────────────────────
  {
    nome_comercial: 'Metil Éster de Coco (FAME)',
    nome_quimico: 'Ácidos graxos metil ésteres de coco',
    numero_cas: '61788-59-8',
    categoria: 'Matérias-primas Sustentáveis',
    subcategoria: 'Biossolventes',
    aparencia: 'Líquido incolor a levemente amarelado',
    ph_solucao: '7.0',
    densidade: '0.87 g/mL',
    solubilidade_agua: 'Insolúvel',
    faixa_uso_tipica: '5% - 30%',
    funcao_principal: 'Biossolvente, lubrificante, formulante de concentrados',
    sinergias: JSON.stringify(['Tensoativos não-iônicos', 'D-Limoneno']),
    incompatibilidades: JSON.stringify(['Oxidantes fortes', 'Bases em alta T°']),
    ph_estabilidade: '5-9',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Muito alta (>90%)',
    origem: 'vegetal',
    certificacoes: JSON.stringify(['Bio-based 100%', 'Biodegradável']),
    fornecedores: JSON.stringify(['Bunge', 'Caramuru', 'Agropalma']),
    custo_min: 5.0,
    custo_max: 12.0,
    disponibilidade: 'alta',
    aplicacoes_tipicas: JSON.stringify(['Biossolventes', 'Limpeza Industrial', 'Automotivo']),
    notas_tecnicas: 'Excelente relação custo-benefício em biossolventes. Origem 100% vegetal. Baixo ponto de fulgor relativo (~100°C).',
  },
  {
    nome_comercial: 'Sorbitano Monooleato (Span 80)',
    nome_quimico: 'Sorbitan monooleato',
    numero_cas: '1338-43-8',
    inci_name: 'Sorbitan Oleate',
    categoria: 'Tensoativos',
    subcategoria: 'Não-iônicos',
    aparencia: 'Líquido viscoso âmbar',
    ph_solucao: '5.0-7.0',
    densidade: '1.01 g/mL',
    solubilidade_agua: 'Insolúvel (dispersível)',
    faixa_uso_tipica: '0.5% - 5%',
    funcao_principal: 'Emulsificante lipofilico W/O, agente de espalhamento',
    sinergias: JSON.stringify(['Polissorbato 80', 'Óleos e ceras']),
    incompatibilidades: JSON.stringify(['Oxidantes fortes']),
    ph_estabilidade: '3-8',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Alta',
    origem: 'vegetal',
    certificacoes: JSON.stringify(['GRAS (FDA)']),
    fornecedores: JSON.stringify(['Croda', 'BASF', 'Evonik']),
    custo_min: 14.0,
    custo_max: 28.0,
    disponibilidade: 'media',
    aplicacoes_tipicas: JSON.stringify(['Biossolventes', 'Cosméticos', 'Limpeza Industrial']),
    notas_tecnicas: 'HLB ~4.3 — emulsificante W/O. Combinado com Polissorbato 80 (HLB ~15) obtém HLB intermediário.',
  },
  // ─── MAIS MATÉRIAS-PRIMAS PARA COMPLETAR 80+ ────────────────────────────
  {
    nome_comercial: 'Ácido Fosfórico 85%',
    nome_quimico: 'Ácido ortofosfórico',
    numero_cas: '7664-38-2',
    categoria: 'Neutralizantes e Tamponantes',
    subcategoria: 'Acidulante mineral',
    aparencia: 'Líquido viscoso incolor a levemente amarelado',
    ph_solucao: '< 1.0',
    densidade: '1.685 g/mL',
    solubilidade_agua: 'Miscível',
    faixa_uso_tipica: '1% - 10%',
    funcao_principal: 'Acidulante, fosfatizante, removedor de ferrugem',
    sinergias: JSON.stringify(['Ácido cítrico', 'Inibidores de corrosão']),
    incompatibilidades: JSON.stringify(['Bases fortes', 'Metais alcalinos']),
    ph_estabilidade: '1-4',
    nivel_toxicidade: 'medio',
    biodegradabilidade: 'N/A (inorgânico)',
    origem: 'mineral',
    fornecedores: JSON.stringify(['Bunge', 'Mosaic', 'Quimibrás']),
    custo_min: 2.5,
    custo_max: 5.0,
    disponibilidade: 'alta',
    aplicacoes_tipicas: JSON.stringify(['Limpeza Industrial', 'Automotivo']),
    notas_tecnicas: 'Fosfatizante de metais (cria camada protetora). Menos volátil e menos perigoso que HCl para remoção de ferrugem.',
  },
  {
    nome_comercial: 'Cloreto de Sódio (NaCl)',
    nome_quimico: 'Cloreto de sódio',
    numero_cas: '7647-14-5',
    categoria: 'Aditivos Funcionais',
    subcategoria: 'Espessantes / reológicos',
    aparencia: 'Cristais brancos',
    ph_solucao: '6.5-7.5',
    densidade: '2.17 g/cm³',
    solubilidade_agua: 'Solúvel (360 g/L)',
    faixa_uso_tipica: '0.5% - 5%',
    funcao_principal: 'Agente de viscosidade (eletrólito) para sistemas SLES',
    sinergias: JSON.stringify(['SLES', 'Betaína de coco']),
    incompatibilidades: JSON.stringify(['Carbopol', 'Goma xantana em excesso']),
    ph_estabilidade: '1-14',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'N/A (inorgânico)',
    origem: 'mineral',
    fornecedores: JSON.stringify(['Salinas do Brasil', 'Cargill']),
    custo_min: 0.5,
    custo_max: 1.5,
    disponibilidade: 'alta',
    aplicacoes_tipicas: JSON.stringify(['Saneantes', 'Limpeza Industrial']),
    notas_tecnicas: 'Efeito "salting-out" — aumenta viscosidade de sistemas SLES entre 1-3%. Curva de viscosidade em U.',
  },
  {
    nome_comercial: 'Ureia',
    nome_quimico: 'Carbamida',
    numero_cas: '57-13-6',
    inci_name: 'Urea',
    categoria: 'Aditivos Funcionais',
    subcategoria: 'Espessantes / reológicos',
    aparencia: 'Cristais brancos',
    ph_solucao: '7.0-8.0',
    densidade: '1.32 g/cm³',
    solubilidade_agua: 'Muito solúvel (1080 g/L)',
    faixa_uso_tipica: '2% - 10%',
    funcao_principal: 'Umectante, desnaturante de proteínas, estabilizante a baixa T°',
    sinergias: JSON.stringify(['Glicerina', 'Propilenoglicol']),
    incompatibilidades: JSON.stringify(['Oxidantes', 'Ácidos nítrico e clorídrico concentrado']),
    ph_estabilidade: '4-9',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Muito alta',
    origem: 'petroleo',
    fornecedores: JSON.stringify(['Petrobras', 'Galena']),
    custo_min: 2.0,
    custo_max: 5.0,
    disponibilidade: 'alta',
    aplicacoes_tipicas: JSON.stringify(['Saneantes', 'Cosméticos']),
    notas_tecnicas: 'Evita congelamento de formulações. Umectante e hidratante. Impede separação de fases em baixas temperaturas.',
  },
  {
    nome_comercial: 'EDTA Dissódico',
    nome_quimico: 'Ácido etilenodiaminotetraacético sal dissódico dihidratado',
    numero_cas: '6381-92-6',
    inci_name: 'Disodium EDTA',
    categoria: 'Aditivos Funcionais',
    subcategoria: 'Sequestrantes / quelantes',
    aparencia: 'Pó branco cristalino',
    ph_solucao: '4.5-5.5',
    densidade: '0.9 g/cm³',
    solubilidade_agua: 'Solúvel (110 g/L)',
    faixa_uso_tipica: '0.05% - 0.5%',
    funcao_principal: 'Sequestrante, quelante, potencializador de conservantes',
    sinergias: JSON.stringify(['Benzalcônio cloreto', 'Parabenos']),
    incompatibilidades: JSON.stringify([]),
    ph_estabilidade: '4-10',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Baixa',
    origem: 'petroleo',
    fornecedores: JSON.stringify(['BASF', 'Galena']),
    custo_min: 10.0,
    custo_max: 20.0,
    disponibilidade: 'alta',
    aplicacoes_tipicas: JSON.stringify(['Cosméticos', 'Saneantes']),
    notas_tecnicas: 'Sequestra Ca2+/Mg2+ e potencializa ação de conservantes. Alternativa: GLDA (biodegradável).',
  },
  {
    nome_comercial: 'Ácido Glucônico 50%',
    nome_quimico: 'Ácido glucônico',
    numero_cas: '526-95-4',
    inci_name: 'Gluconic Acid',
    categoria: 'Aditivos Funcionais',
    subcategoria: 'Sequestrantes / quelantes',
    aparencia: 'Líquido viscoso levemente amarelado',
    ph_solucao: '3.0-4.0',
    densidade: '1.25 g/mL',
    solubilidade_agua: 'Miscível',
    faixa_uso_tipica: '0.5% - 3%',
    funcao_principal: 'Quelante suave bio-based, acidulante, inibidor de manchas',
    sinergias: JSON.stringify(['GLDA', 'Ácido cítrico']),
    incompatibilidades: JSON.stringify(['Bases fortes']),
    ph_estabilidade: '3-10',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Muito alta',
    origem: 'bio-sintetico',
    certificacoes: JSON.stringify(['GRAS', 'Ecocert elegível']),
    fornecedores: JSON.stringify(['Jungbunzlauer', 'Roquette']),
    custo_min: 8.0,
    custo_max: 18.0,
    disponibilidade: 'media',
    aplicacoes_tipicas: JSON.stringify(['Limpeza Industrial', 'Saneantes']),
    notas_tecnicas: 'Quelante biodegradável. Origem fermentativa da glicose. Boa em formulações para claims verdes.',
  },
  {
    nome_comercial: 'Tensoativo Anfótero (CAPB)',
    nome_quimico: 'Cocamidopropil betaína (ver Betaína de Coco)',
    numero_cas: '61789-40-0',
    inci_name: 'Cocamidopropyl Betaine',
    categoria: 'Tensoativos',
    subcategoria: 'Anfóteros / Zwitteriônicos',
    aparencia: 'Líquido âmbar claro',
    ph_solucao: '4.5-6.5',
    densidade: '1.05 g/mL',
    solubilidade_agua: 'Solúvel',
    faixa_uso_tipica: '3% - 15%',
    funcao_principal: 'Co-surfactante anfótero, estabilizador de espuma, suavizante',
    sinergias: JSON.stringify(['SLES', 'SLS', 'APG']),
    incompatibilidades: JSON.stringify([]),
    ph_estabilidade: '3-12',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Alta',
    origem: 'vegetal',
    fornecedores: JSON.stringify(['Oxiteno', 'Evonik']),
    custo_min: 10.0,
    custo_max: 20.0,
    disponibilidade: 'alta',
    aplicacoes_tipicas: JSON.stringify(['Saneantes', 'Cosméticos']),
    notas_tecnicas: 'Ver Betaína de Coco. Sinônimo comercial mais técnico.',
  },
  {
    nome_comercial: 'Molibidata de Sódio',
    nome_quimico: 'Molibdato de sódio dihidratado',
    numero_cas: '10102-40-6',
    categoria: 'Aditivos Funcionais',
    subcategoria: 'Inibidores de corrosão',
    aparencia: 'Cristais brancos',
    ph_solucao: '9.0-10.0',
    densidade: '3.28 g/cm³',
    solubilidade_agua: 'Solúvel (650 g/L)',
    faixa_uso_tipica: '0.05% - 0.5%',
    funcao_principal: 'Inibidor anódico de corrosão para aço e liga de alumínio',
    sinergias: JSON.stringify(['Benzotriazol', 'Silicato de sódio']),
    incompatibilidades: JSON.stringify(['Ácidos fortes', 'Agentes redutores']),
    ph_estabilidade: '6-12',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'N/A (inorgânico)',
    origem: 'mineral',
    fornecedores: JSON.stringify(['H.C. Starck', 'Climax Molybdenum']),
    custo_min: 40.0,
    custo_max: 90.0,
    disponibilidade: 'baixa',
    aplicacoes_tipicas: JSON.stringify(['Limpeza Industrial', 'Automotivo']),
    notas_tecnicas: 'Substituto não tóxico do cromato. Eficaz em concentrações muito baixas (50-200 ppm).',
  },
  {
    nome_comercial: 'Fosfato de Zinco',
    nome_quimico: 'Ortofosfato de zinco',
    numero_cas: '7779-90-0',
    categoria: 'Aditivos Funcionais',
    subcategoria: 'Inibidores de corrosão',
    aparencia: 'Pó branco',
    ph_solucao: 'N/A (insolúvel)',
    densidade: '3.99 g/cm³',
    solubilidade_agua: 'Praticamente insolúvel',
    faixa_uso_tipica: '5% - 25% (em tintas)',
    funcao_principal: 'Pigmento anticorrosivo em tintas e primers',
    sinergias: JSON.stringify(['Resinas epóxi', 'Resinas alquídicas']),
    incompatibilidades: JSON.stringify(['Ácidos fortes (solubiliza)']),
    ph_estabilidade: '6-10',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'N/A (inorgânico)',
    origem: 'mineral',
    fornecedores: JSON.stringify(['Heucotech', 'Shieldex']),
    custo_min: 15.0,
    custo_max: 35.0,
    disponibilidade: 'media',
    aplicacoes_tipicas: JSON.stringify(['Tintas e Vernizes']),
    notas_tecnicas: 'Substituto não tóxico do cromato de zinco em primers anticorrosivos. Exige moagem fina (<10 μm).',
  },
  {
    nome_comercial: 'Poliuretano Aquoso Disperso',
    nome_quimico: 'Dispersão aquosa de poliuretano (PUD)',
    numero_cas: '9009-54-5',
    categoria: 'Resinas e Polímeros',
    subcategoria: 'Poliuretanos',
    aparencia: 'Dispersão branca leitosa',
    ph_solucao: '7.0-9.0',
    densidade: '1.04 g/mL',
    solubilidade_agua: 'Dispersão aquosa',
    faixa_uso_tipica: '30% - 60%',
    funcao_principal: 'Ligante aquoso de alta resistência, acabamentos flexíveis',
    sinergias: JSON.stringify(['Coalescentes', 'Isocianatos bloqueados']),
    incompatibilidades: JSON.stringify(['pH < 5', 'Ácidos concentrados', 'Aminas voláteis']),
    ph_estabilidade: '6-10',
    nivel_toxicidade: 'baixo',
    biodegradabilidade: 'Baixa',
    origem: 'petroleo',
    fornecedores: JSON.stringify(['Bayer', 'Dow', 'Alberdingk Boley']),
    custo_min: 20.0,
    custo_max: 50.0,
    disponibilidade: 'media',
    aplicacoes_tipicas: JSON.stringify(['Tintas e Vernizes', 'Biossolventes']),
    notas_tecnicas: 'Alta flexibilidade e resistência à abrasão. Base aquosa — baixo VOC. Pode ser 2K com isocianato.',
  },
]

function makeId(nome: string): string {
  return nome.toLowerCase().replace(/[\s()/%]/g, '-').replace(/--+/g, '-').replace(/[^a-z0-9-]/g, '').slice(0, 25)
}

async function main() {
  console.log('Iniciando seed do banco de matérias-primas...')

  for (const mp of materiasPrimas) {
    const id = makeId(mp.nome_comercial)
    await prisma.materiaPrima.upsert({
      where: { id },
      update: mp,
      create: { id, ...mp },
    })
  }

  console.log(`✅ Seed completo: ${materiasPrimas.length} matérias-primas cadastradas`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
